# Generated by Django 5.0.4 on 2024-05-28 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Atestados', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atestado',
            name='arquivo',
            field=models.FileField(upload_to='atestados/uploads/%Y/%m/%d/'),
        ),
    ]
